#centlee  630628
#自定义
gms:
  version: v1
  test: true    #测试时设置为false

#服务器
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

#spring
spring:
  datasource:
    dynamic:
      p6spy: true  #sql打印开关
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        pool-name: GmsHikariCP
      #设置默认数据源
      primary: base
      datasource:
        base:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver  #192.168.42.11
          url: jdbc:mysql://192.168.42.10:3306/gms_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
        quartz:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.42.10:3306/gms_quartz?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

  rabbitmq:
    virtual-host: /
    host: 192.168.42.10
    username: gms
    password: 123456
    port: 5672
    requested-heartbeat: 60
    connection-timeout: 10000
    listener:
      simple:
        retry:
          enabled: true     #开启重试
          max-attempts: 3   #最大重试次数
          initial-interval: 1000  #重试时间间隔,ms
        default-requeue-rejected: true  #重试超过设置次数后是否丢弃

  redis:
    database: 0
    host: 192.168.42.10
    port: 6379
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active: 8         #连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000       #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8           # 连接池中的最大空闲连接
        min-idle: 0           # 连接池中的最小空闲连接
      shutdown-timeout: 100   # 关闭超时时间

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  devtools:
#    restart:
#      additional-paths: src/main/java #设置重启的目录
#      additional-exclude: WEB-INF/**  #classpath目录下的WEB-INF文件夹内容修改不重启
#      enabled: true                   #热部署生效


#mybatis-plus
mybatis-plus:
  type-aliases-package: com.zs.gms.entity.*.*     # 实体类扫描路径
  mapper-locations: classpath:mapper/*/*.xml    # xml 扫描路径
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler     #枚举类型指定转换器
    jdbc-type-for-null: null

    #map-underscore-to-camel-case: false   #驼峰转下划线
  global-config:
    banner: false      #关闭 mybatis-plus的 banner

#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*" #配置监控开启的端点

#log
logging:
  level:
    #com.zs.gms.common.handler: debug   #设置全局异常的日志级别
    com.zs.gms: debug